version: '3'

services:
  winman:
    build:
      args:
        source: obj/Docker/publish/
    volumes:
      - :C:\remote_debugger:ro
    entrypoint: cmd /c "set DISABLE_PERFORMANCE_DEBUGGER=1 & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    labels:
      com.microsoft.visualstudio.debuggee.program: "C:\\app\\WinMan.exe"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
