using DeploymentToolkit.Scripting.PreProcessorFunctions;
using System;
using System.Collections.Generic;

namespace DeploymentToolkit.Scripting
{
    public static partial class PreProcessor
    {
        private static readonly Dictionary<string, Func<string[], string>> _functions = new Dictionary<string, Func<string[], string>>()
        {
            #region FileFunctions
            {
                "FileExists",
                FileFunctions.Exists
            },
            {
                "FileMove",
                FileFunctions.MoveFile
            },
            {
                "FileCopy",
                FileFunctions.CopyFile
            },
            {
                "FileCopyForAllUsers",
                FileFunctions.CopyFileForAllUsers
            },
            {
                "DeleteFile",
                FileFunctions.DeleteFile
            },
            {
                "DeleteFileForAllUsers",
                FileFunctions.DeleteFileForAllUsers
            },
            #endregion
            #region DirectoryFunctions
            {
                "DirectoryExists",
                DirectoryFunctions.Exists
            },
            {
                "DirectoryMove",
                DirectoryFunctions.MoveDirectory
            },
            {
                "DirectoryCopy",
                DirectoryFunctions.CopyDirectory
            },
            {
                "DirectoryCopyForAllUsers",
                DirectoryFunctions.CopyDirectoryForAllUsers
            },
            {
                "DirectoryDelete",
                DirectoryFunctions.DeleteDirectory
            },
            {
                "DirectoryDeleteForAllUsers",
                DirectoryFunctions.DeleteDirectoryForAllUsers
            },
            {
                "DirectoryCreate",
                DirectoryFunctions.CreateDirectory
            },
            {
                "DirectoryCreateForAllUsers",
                DirectoryFunctions.CreateDirectoryForAllUsers
            },
            #endregion
            #region RegistryFunctions
            {
                "RegHasKey",
                RegistryFunctions.HasKey
            },
            {
                "RegCreateKey",
                RegistryFunctions.CreateKey
            },
            {
                "RegCreateKeyForAllUsers",
                RegistryFunctions.CreateKeyForAllUsers
            },
            {
                "RegDeleteKey",
                RegistryFunctions.DeleteKey
            },
            {
                "RegDeleteKeyForAllUsers",
                RegistryFunctions.DeleteKeyForAllUsers
            },
            {
                "RegHasValue",
                RegistryFunctions.HasValue
            },
            {
                "RegGetValue",
                RegistryFunctions.GetValue
            },
            {
                "RegSetValue",
                RegistryFunctions.SetValue
            },
            {
                "RegSetValueForAllUsers",
                RegistryFunctions.SetValueForAllUsers
            },
            {
                "RegDeleteValue",
                RegistryFunctions.DeleteValue
            },
            {
                "RegDeleteValueForAllUsers",
                RegistryFunctions.DeleteValueForAllUsers
            }
            #endregion
        };
    }
}
