//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wsus_Package_Publisher.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wsus_Package_Publisher.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate here the informations about the update. Fields in bold are required.
        ///
        ///Vendor Name (Required): It is here that you define the name of the publisher of the update. For example: Oracle, Sun, Symantec, Adobe ...
        ///
        ///Product Name (Required): Name of the upgraded product. For example: Java, Endpoint Protection 12, Flash Player ...
        ///
        ///Title (Required): It is here that you define the title of the update. For example: Java 6 update 31, Symantec Endpoint Protection 12.1 MP1 RU1, Flash Player 11.2.0.233 ...
        ///
        ///Descr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionInformationsWizard {
            get {
                return ResourceManager.GetString("DescriptionInformationsWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicate here the file  or files to create the update. Fields in bold are required.
        ///
        ///File update (Required): Select a msi, msp or exe file corresponding to the binary update.
        ///
        ///Additional files (Optional): Select a file or files needed for the application of the update. For example configuration files or answer file.
        ///
        ///Command line (Optional): Indicate one or more parameters for the file update. Eg /q /s or /silent. For Msi file it is not necessary to specify the option to make the installation silent. Wsus d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DescriptionUpdateFileWizard {
            get {
                return ResourceManager.GetString("DescriptionUpdateFileWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All accepted files|*.msi;*.msp;*.exe|MSI Files|*.msi|MSP Files|*.msp|EXE Files|*.exe.
        /// </summary>
        internal static string openFileDialogueUpdateFile {
            get {
                return ResourceManager.GetString("openFileDialogueUpdateFile", resourceCulture);
            }
        }
    }
}
