//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomActions.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomActionsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomActionsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomActions.Localization.CustomActionsStrings", typeof(CustomActionsStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a .
        /// </summary>
        internal static string AddA {
            get {
                return ResourceManager.GetString("AddA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add this Registry Key : .
        /// </summary>
        internal static string AddThisRegKey {
            get {
                return ResourceManager.GetString("AddThisRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and kill the process if it run more than .
        /// </summary>
        internal static string AndKillProcessIfItRunMoreThan {
            get {
                return ResourceManager.GetString("AndKillProcessIfItRunMoreThan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and store the return code to the variable..
        /// </summary>
        internal static string AndStoreReturnCodeToVariable {
            get {
                return ResourceManager.GetString("AndStoreReturnCodeToVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        internal static string Automatic {
            get {
                return ResourceManager.GetString("Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the Registry Data : .
        /// </summary>
        internal static string ChangeRegData {
            get {
                return ResourceManager.GetString("ChangeRegData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the starting mode of .
        /// </summary>
        internal static string ChangeTheStartingModeOf {
            get {
                return ResourceManager.GetString("ChangeTheStartingModeOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configured.
        /// </summary>
        internal static string Configured {
            get {
                return ResourceManager.GetString("Configured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy the file .
        /// </summary>
        internal static string CopyTheFile {
            get {
                return ResourceManager.GetString("CopyTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the folder .
        /// </summary>
        internal static string CreateTheFolder {
            get {
                return ResourceManager.GetString("CreateTheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create the text file .
        /// </summary>
        internal static string CreateTheTextFile {
            get {
                return ResourceManager.GetString("CreateTheTextFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a shortcut named .
        /// </summary>
        internal static string CreateThisShortcut {
            get {
                return ResourceManager.GetString("CreateThisShortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete .
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the file .
        /// </summary>
        internal static string DeleteTheFile {
            get {
                return ResourceManager.GetString("DeleteTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the folder .
        /// </summary>
        internal static string DeleteTheFolder {
            get {
                return ResourceManager.GetString("DeleteTheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this registry key : .
        /// </summary>
        internal static string DeleteThisRegKey {
            get {
                return ResourceManager.GetString("DeleteThisRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete the scheduled task : .
        /// </summary>
        internal static string DeleteThisTask {
            get {
                return ResourceManager.GetString("DeleteThisTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to add a Registry Key..
        /// </summary>
        internal static string DescriptionAddRegKeyAction {
            get {
                return ResourceManager.GetString("DescriptionAddRegKeyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to add a Registry Value..
        /// </summary>
        internal static string DescriptionAddRegValueAction {
            get {
                return ResourceManager.GetString("DescriptionAddRegValueAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to change a Data in a Registry Value..
        /// </summary>
        internal static string DescriptionChangeRegDataAction {
            get {
                return ResourceManager.GetString("DescriptionChangeRegDataAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to change the starting mode of a service..
        /// </summary>
        internal static string DescriptionChangeServiceAction {
            get {
                return ResourceManager.GetString("DescriptionChangeServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to copy a file..
        /// </summary>
        internal static string DescriptionCopyFileAction {
            get {
                return ResourceManager.GetString("DescriptionCopyFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to create a folder..
        /// </summary>
        internal static string DescriptionCreateFolderAction {
            get {
                return ResourceManager.GetString("DescriptionCreateFolderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to create a shortcut.
        /// </summary>
        internal static string DescriptionCreateShortcutAction {
            get {
                return ResourceManager.GetString("DescriptionCreateShortcutAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to create a text file..
        /// </summary>
        internal static string DescriptionCreateTextFileAction {
            get {
                return ResourceManager.GetString("DescriptionCreateTextFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to delete a file..
        /// </summary>
        internal static string DescriptionDeleteFileAction {
            get {
                return ResourceManager.GetString("DescriptionDeleteFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to delete a folder..
        /// </summary>
        internal static string DescriptionDeleteFolderAction {
            get {
                return ResourceManager.GetString("DescriptionDeleteFolderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to delete a Registry Key..
        /// </summary>
        internal static string DescriptionDeleteRegKeyAction {
            get {
                return ResourceManager.GetString("DescriptionDeleteRegKeyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to delete a Registry Value..
        /// </summary>
        internal static string DescriptionDeleteRegValueAction {
            get {
                return ResourceManager.GetString("DescriptionDeleteRegValueAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to delete a scheduled task.
        /// </summary>
        internal static string DescriptionDeleteTask {
            get {
                return ResourceManager.GetString("DescriptionDeleteTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to execute a file..
        /// </summary>
        internal static string DescriptionExecutableAction {
            get {
                return ResourceManager.GetString("DescriptionExecutableAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import a .reg file..
        /// </summary>
        internal static string DescriptionImportRegFileAction {
            get {
                return ResourceManager.GetString("DescriptionImportRegFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to install a MSI application.
        /// </summary>
        internal static string DescriptionInstallMsi {
            get {
                return ResourceManager.GetString("DescriptionInstallMsi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to kill a process..
        /// </summary>
        internal static string DescriptionKillProcessAction {
            get {
                return ResourceManager.GetString("DescriptionKillProcessAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to reboot the computer..
        /// </summary>
        internal static string DescriptionRebootAction {
            get {
                return ResourceManager.GetString("DescriptionRebootAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to register a DLL..
        /// </summary>
        internal static string DescriptionRegisterDLLAction {
            get {
                return ResourceManager.GetString("DescriptionRegisterDLLAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to rename a file..
        /// </summary>
        internal static string DescriptionRenameFileAction {
            get {
                return ResourceManager.GetString("DescriptionRenameFileAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alllows to rename a folder..
        /// </summary>
        internal static string DescriptionRenameFolderAction {
            get {
                return ResourceManager.GetString("DescriptionRenameFolderAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to rename a Registry key..
        /// </summary>
        internal static string DescriptionRenameRegKeyAction {
            get {
                return ResourceManager.GetString("DescriptionRenameRegKeyAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to rename a Registry Value..
        /// </summary>
        internal static string DescriptionRenameRegValueAction {
            get {
                return ResourceManager.GetString("DescriptionRenameRegValueAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to set a return code to send when finished..
        /// </summary>
        internal static string DescriptionReturnCodeAction {
            get {
                return ResourceManager.GetString("DescriptionReturnCodeAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to run a Powershell script..
        /// </summary>
        internal static string DescriptionRunPowershellScriptAction {
            get {
                return ResourceManager.GetString("DescriptionRunPowershellScriptAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to run a VbScript..
        /// </summary>
        internal static string DescriptionRunVBScriptAction {
            get {
                return ResourceManager.GetString("DescriptionRunVBScriptAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to shutdown the computer..
        /// </summary>
        internal static string DescriptionShutdownAction {
            get {
                return ResourceManager.GetString("DescriptionShutdownAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to start a service..
        /// </summary>
        internal static string DescriptionStartServiceAction {
            get {
                return ResourceManager.GetString("DescriptionStartServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to stop a service..
        /// </summary>
        internal static string DescriptionStopServiceAction {
            get {
                return ResourceManager.GetString("DescriptionStopServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to uninstall a MSI product by knowing his Guid..
        /// </summary>
        internal static string DescriptionUinstallMsiProductByGuid {
            get {
                return ResourceManager.GetString("DescriptionUinstallMsiProductByGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow to uninstall MSI applications by knowing their name.
        /// </summary>
        internal static string DescriptionUninstallMsiProductByNameAction {
            get {
                return ResourceManager.GetString("DescriptionUninstallMsiProductByNameAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to unregister a DLL..
        /// </summary>
        internal static string DescriptionUnregisterDLLAction {
            get {
                return ResourceManager.GetString("DescriptionUnregisterDLLAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to Unregister a service..
        /// </summary>
        internal static string DescriptionUnregisterServiceAction {
            get {
                return ResourceManager.GetString("DescriptionUnregisterServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows to wait an amount of time..
        /// </summary>
        internal static string DescriptionWaitAction {
            get {
                return ResourceManager.GetString("DescriptionWaitAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable.
        /// </summary>
        internal static string Disable {
            get {
                return ResourceManager.GetString("Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute the file .
        /// </summary>
        internal static string ExecuteTheFile {
            get {
                return ResourceManager.GetString("ExecuteTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute the Powershell script .
        /// </summary>
        internal static string ExecuteThePowershellScript {
            get {
                return ResourceManager.GetString("ExecuteThePowershellScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute the VbScript .
        /// </summary>
        internal static string ExecuteTheVbScript {
            get {
                return ResourceManager.GetString("ExecuteTheVbScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import the file : .
        /// </summary>
        internal static string ImportTheFile {
            get {
                return ResourceManager.GetString("ImportTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  in .
        /// </summary>
        internal static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install .
        /// </summary>
        internal static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  into .
        /// </summary>
        internal static string Into {
            get {
                return ResourceManager.GetString("Into", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kill the process : .
        /// </summary>
        internal static string KillProcess {
            get {
                return ResourceManager.GetString("KillProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        internal static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to misconfigured.
        /// </summary>
        internal static string Misconfigured {
            get {
                return ResourceManager.GetString("Misconfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No help available for this Action..
        /// </summary>
        internal static string NoHelpAvailable {
            get {
                return ResourceManager.GetString("NoHelpAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not configured.
        /// </summary>
        internal static string NotConfigured {
            get {
                return ResourceManager.GetString("NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reboot the computer..
        /// </summary>
        internal static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register this DLL : .
        /// </summary>
        internal static string RegisterDLL {
            get {
                return ResourceManager.GetString("RegisterDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  registry value named .
        /// </summary>
        internal static string RegValueNamed {
            get {
                return ResourceManager.GetString("RegValueNamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename the file.
        /// </summary>
        internal static string RenameTheFile {
            get {
                return ResourceManager.GetString("RenameTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename the folder .
        /// </summary>
        internal static string RenameTheFolder {
            get {
                return ResourceManager.GetString("RenameTheFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename this Registry Key : .
        /// </summary>
        internal static string RenameThisRegKey {
            get {
                return ResourceManager.GetString("RenameThisRegKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename this Registry value : .
        /// </summary>
        internal static string RenameThisRegValue {
            get {
                return ResourceManager.GetString("RenameThisRegValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always restart.
        /// </summary>
        internal static string RestartLevel_Force {
            get {
                return ResourceManager.GetString("RestartLevel_Force", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No restart.
        /// </summary>
        internal static string RestartLevel_None {
            get {
                return ResourceManager.GetString("RestartLevel_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prompt user if needed.
        /// </summary>
        internal static string RestartLevel_Prompt {
            get {
                return ResourceManager.GetString("RestartLevel_Prompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always return the code : .
        /// </summary>
        internal static string ReturnStaticCode {
            get {
                return ResourceManager.GetString("ReturnStaticCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return the code previously stored in the variable..
        /// </summary>
        internal static string ReturnVariable {
            get {
                return ResourceManager.GetString("ReturnVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to seconds.
        /// </summary>
        internal static string Seconds {
            get {
                return ResourceManager.GetString("Seconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shutdown the computer..
        /// </summary>
        internal static string Shutdown {
            get {
                return ResourceManager.GetString("Shutdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start the service : .
        /// </summary>
        internal static string StartTheService {
            get {
                return ResourceManager.GetString("StartTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop the service : .
        /// </summary>
        internal static string StopTheService {
            get {
                return ResourceManager.GetString("StopTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Xml Element &apos;{0}&apos; has not been match with any properties of &apos;{1}&apos;.
        /// </summary>
        internal static string TheXmlElementHasNotBeenMatchWithProperty {
            get {
                return ResourceManager.GetString("TheXmlElementHasNotBeenMatchWithProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Action does nothing..
        /// </summary>
        internal static string ThisActionDoesNothing {
            get {
                return ResourceManager.GetString("ThisActionDoesNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Action is.
        /// </summary>
        internal static string ThisActionIs {
            get {
                return ResourceManager.GetString("ThisActionIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action refers to a user profile..
        /// </summary>
        internal static string ThisActionRefersToUserProfile {
            get {
                return ResourceManager.GetString("ThisActionRefersToUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to .
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basic UI.
        /// </summary>
        internal static string UILevel_Base {
            get {
                return ResourceManager.GetString("UILevel_Base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full UI.
        /// </summary>
        internal static string UILevel_Full {
            get {
                return ResourceManager.GetString("UILevel_Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No UI.
        /// </summary>
        internal static string UILevel_None {
            get {
                return ResourceManager.GetString("UILevel_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduced UI.
        /// </summary>
        internal static string UILevel_Reduced {
            get {
                return ResourceManager.GetString("UILevel_Reduced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall the application : {0} with parameters {1}.
        /// </summary>
        internal static string UninstallThisMsiApplication {
            get {
                return ResourceManager.GetString("UninstallThisMsiApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister the service : .
        /// </summary>
        internal static string UnregisterTheService {
            get {
                return ResourceManager.GetString("UnregisterTheService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unregister this DLL : .
        /// </summary>
        internal static string UnregisterThisDLL {
            get {
                return ResourceManager.GetString("UnregisterThisDLL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wait.
        /// </summary>
        internal static string Wait {
            get {
                return ResourceManager.GetString("Wait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  which content .
        /// </summary>
        internal static string whichContent {
            get {
                return ResourceManager.GetString("whichContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  which target .
        /// </summary>
        internal static string WhichTarget {
            get {
                return ResourceManager.GetString("WhichTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with the content : .
        /// </summary>
        internal static string WithContent {
            get {
                return ResourceManager.GetString("WithContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to with parameters .
        /// </summary>
        internal static string WithParameters {
            get {
                return ResourceManager.GetString("WithParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  with the data : .
        /// </summary>
        internal static string WithTheData {
            get {
                return ResourceManager.GetString("WithTheData", resourceCulture);
            }
        }
    }
}
