//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomUpdateCreator.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CustomUpdateCreatorStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomUpdateCreatorStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CustomUpdateCreator.Localization.CustomUpdateCreatorStrings", typeof(CustomUpdateCreatorStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An Action store its return code in the variable but the update returns a static code..
        /// </summary>
        internal static string ActionWithReturnCodeAndUpdateWithStaticMethod {
            get {
                return ResourceManager.GetString("ActionWithReturnCodeAndUpdateWithStaticMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurs while initializing : .
        /// </summary>
        internal static string AnErrorOccursWhileIntializingAction {
            get {
                return ResourceManager.GetString("AnErrorOccursWhileIntializingAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurs while saving Template : .
        /// </summary>
        internal static string AnErrorOccursWhileSavingTemplate {
            get {
                return ResourceManager.GetString("AnErrorOccursWhileSavingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create an isntance of this Action : .
        /// </summary>
        internal static string CannotCreateAnInstanceOfThisAction {
            get {
                return ResourceManager.GetString("CannotCreateAnInstanceOfThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the file : .
        /// </summary>
        internal static string CannotFindTheFile {
            get {
                return ResourceManager.GetString("CannotFindTheFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Xml element &apos;CustomActionTemplate&apos; cannot be found..
        /// </summary>
        internal static string CustomUpdateFileBadlyFormated {
            get {
                return ResourceManager.GetString("CustomUpdateFileBadlyFormated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the current Custom Update ?.
        /// </summary>
        internal static string DoYouWantToSaveCurrentCustomUpdate {
            get {
                return ResourceManager.GetString("DoYouWantToSaveCurrentCustomUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurs while loading Template : .
        /// </summary>
        internal static string ErrorLoadingTemplate {
            get {
                return ResourceManager.GetString("ErrorLoadingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It will have default value..
        /// </summary>
        internal static string ItWillHaveDefaultValues {
            get {
                return ResourceManager.GetString("ItWillHaveDefaultValues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is more than one Action to store its return code into the variable..
        /// </summary>
        internal static string MoreThanOneActionWithReturnCode {
            get {
                return ResourceManager.GetString("MoreThanOneActionWithReturnCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Custom Update must have, at least, one Action..
        /// </summary>
        internal static string NoActionInThisCustomUpdate {
            get {
                return ResourceManager.GetString("NoActionInThisCustomUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved.
        /// </summary>
        internal static string saved {
            get {
                return ResourceManager.GetString("saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Custom Update that returns the contains of the variable must have an action that store its return code in the variable..
        /// </summary>
        internal static string TheVariableIsNeverFill {
            get {
                return ResourceManager.GetString("TheVariableIsNeverFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Action has not been recognized : .
        /// </summary>
        internal static string ThisActionHasNotBeenRecognized {
            get {
                return ResourceManager.GetString("ThisActionHasNotBeenRecognized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Action is not properly configurated..
        /// </summary>
        internal static string ThisActionIsNotProperlyConfigurated {
            get {
                return ResourceManager.GetString("ThisActionIsNotProperlyConfigurated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set ReturnCode from the Template..
        /// </summary>
        internal static string UnableToSetReturnCodeFromXmlFile {
            get {
                return ResourceManager.GetString("UnableToSetReturnCodeFromXmlFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unnamed.CustAct.
        /// </summary>
        internal static string unnamed {
            get {
                return ResourceManager.GetString("unnamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsaved.
        /// </summary>
        internal static string unsaved {
            get {
                return ResourceManager.GetString("unsaved", resourceCulture);
            }
        }
    }
}
